### PR TITLE
More verbose nosetests

### PR DESCRIPTION
**Pull request by hassanshamim**
Hey dude, I noticed you started doing some refactoring and I thought you might find these tests useful that  I wrote for myself anyway because I'm using your library.  Also some PEP8 formatting so my editor would stop scolding me.

I realize they're verbose but I just call that thorough 😉 .  Anyway take 'em or leave 'em, I won't be offended.  Though I'd take a look at the changes to the handler decorators.  You don't need to actually return the function wrapper as you're not actually modifying the function at all.  Also default handler takes a func as the arg so you don't have to instantiate it.

Thanks again for the library btw.

### CODE REVIEW

**Comment by anjishnu** [comment]
Thanks for the work - I have been lazy in writing tests, and I have no business nitpicking someone else's!

**Comment by hassanshamim** [comment]
I've got some free time tomorrow if you'd like I can freshen these up a bit to be compatible with your master branch.

**Comment by anjishnu** [comment]
I'm out tomorrow, but if you make the change I could take a look on monday.

**Comment by hassanshamim** [comment]
sounds good

**Comment by hassanshamim** [comment]
tests are passing again.  rebased so it'd be a clean merge.

**Pull request merged**
